import 'package:dio/dio.dart';
import 'package:m_skool_flutter/constants/api_url_constants.dart';
import 'package:m_skool_flutter/controller/global_utilities.dart';
import 'package:m_skool_flutter/main.dart';
import 'package:m_skool_flutter/vms/security/controller/security_controller.dart';
import 'package:m_skool_flutter/vms/security/model/model.dart';

Future<int> feacthSecurityApi({
  required String base,
  required int ivrmrtId,
  required int userId,
  required int mi_id,
  required SecurtyWorkController controller,
}) async {
  final Dio ins = getGlobalDio();
  final String apiUrl =
       "https://vmsissuemanager.azurewebsites.net/"+URLS.Security;
    logger.d("damn ${apiUrl}");
   try {
    controller.updateLoading(true);

    final Response response = await ins.post(apiUrl,
        options: Options(headers: getSession()),
        data: {
        "UserId": 60737,
        "Auto_id": null,
        "Minor": null,
        "Blocker": null,
        "Critical": null,
        "Major": null,
        "DepartmentName": null,
        "ISMMAC_Id": 0,
        "MI_Id": 17,
        "Role_flag": null,
        "flag": null,
        "yearid": 0,
        "month": 0,
        "employeename": null,
        "HRME_Photo": null,
        "departmnt": null,
        "desgination": null,
        "gradename": null,
        "approvedBy": null,
        "emailid": null,
        "FOEPD_InOutFlg": null,
        "ISMDRPT_Date": null,
        "IVRMRT_Id": 32,
        "ASMAY_Id": 125,
        "HRMD_Id": null,
        "HRMDES_Id": null,
        "ISMMPR_Id": 0,
        "ISMMPR_ProjectName": null,
        "HRME_Id": 0,
        "HRME_EmployeeFirstName": null,
        "HRME_EmployeeCode": 0,
        "Status": null,
        "HRME_EmployeeMiddleName": null,
        "HRME_EmployeeLastName": null,
        "HRMD_DepartmentName": null,
        "HRMDES_DesignationName": null,
        "IVRMM_Id": 0,
        "IVRMM_ModuleName": null,
        "IVRMM_ModuleDesc": null,
        "ISMMMD_Id": 0,
        "ISMMCLT_Id": 0,
        "ISMMCLT_ClientName": null,
        "ISMTCR_Id": 0,
        "ISMTCR_TaskNo": null,
        "ISMTCR_BugOREnhancementFlg": null,
        "ISMTCR_CreationDate": null,
        "ISMTCR_Title": null,
        "HRMPR_Id": 0,
        "HRMP_Name": null,
        "message": null,
        "ISMTCR_Desc": null,
        "ISMTCR_Status": null,
        "ISMTCR_ReOpenFlg": false,
        "ISMTCR_ReOpenDate": null,
        "ISMTCRASTO_Id": 0,
        "ISMTCRASTO_AssignedDate": "0001-01-01T00:00:00",
        "ISMTCRASTO_AssignedBy": 0,
        "ISMTCRASTO_Remarks": null,
        "ISMTCRASTO_StartDate": null,
        "ISMTCRASTO_EndDate": null,
        "ISMTCRASTO_EffortInHrs": 0,
        "ISMTCRASTO_ActiveFlg": false,
        "assignedby": null,
        "approvedby": null,
        "ISMTPLTA_EffortInHrsnew": null,
        "DeviceID": null,
        "ISMTPLTA_Id": 0,
        "ISMTPL_Id": 0,
        "ISMTPLTA_Remarks": null,
        "ISMTPLTA_StartDate": null,
        "ISMTPLTA_EndDate": null,
        "ISMTPLTA_EffortInHrs": 0,
        "ISMTPLTA_FinishedDate": null,
        "ISMTPLAPTA_Id": 0,
        "HRELS_TotalLeaves": 0.0,
        "HRELS_CBLeaves": 0.0,
        "FOMHWDD_Name": null,
        "FOHTWD_HolidayWDType": null,
        "MI_Name": null,
        "totalcount": 0,
        "FOMHWDD_FromDate": null,
        "IsmDashBoard": null,
        "projectCount": 0,
        "taskCount": 0,
        "openCount": 0,
        "closedCount": 0,
        "completedCount": 0,
        "inprogressCount": 0,
        "holidaylist": null,
        "employeedetails": null,
        "birthdaylist": null,
        "leavedetails": null,
        "upcomingholiday": null,
        "lateindata": null,
        "lateindataprevious": null,
        "attendancedata": null,
        "pushnotification": null,
        "HRME_DOB": null,
        "FOEP_Id": 0,
        "FOEP_PunchDate": null,
        "lastpunchdate": null,
        "getdeviationreport": null,
        "punchdetails": null,
        "punchdetailsprevious": null,
        "visitorcheckoutdetails": null,
        "totdayspresent": 0,
        "totholiday": 0,
        "projectcount": null,
        "totalopentask": null,
        "totalinprogresstask": null,
        "totalpendingtask": null,
        "fromdate": "0001-01-01T00:00:00",
        "todate": "0001-01-01T00:00:00",
        "getabsentlist": null,
        "issueslist": null,
        "prioritylist": null,
        "prioritylistadmin": null,
        "prioritypivot": null,
        "eventlist": null,
        "getdeviationdepartmentwise": null,
        "plannernotgeneratedreport": null,
        "totapplied": null,
        "totapproved": null,
        "totrejected": null,
        "totpending": null,
        "blocklist": null,
        "totalemployees": null,
        "HRMEMNO_MobileNo": 0,
        "checkdeptheadcode": 0,
        "mappedemployeedetails": null,
        "mappedemployeeissuedetails": null,
        "get_statuslist": null,
        "interdeptmenttasklist": null,
        "getadvancetada": null,
        "TypeFlg": null,
        "planerapproval": null,
        "drnotapprovedmessage": null,
        "Laptopnotapprovedlist": null,
        "blockeddetails": null,
        "DR_NotApprovedTL": 1,
        "blockedcount": 0,
        "DashbaordAttendanceDetailsCount": null,
        "DashbaordPlannerDetailsCount": null,
        "DashbaordPlannerApprovedDetailsCount": null,
        "DashbaordPettyCashDetailsCount": null,
        "DashbaordHrmssalaryDetailsCount": null,
        "DashbaordInventoryDetailsCount": null,
        "DashboardLeaveDetailsCount": null,
        "DashboardPurchaseIndentaseDetailsCount": null,
        "DashboardPurchaseOrderDetailsCount": null,
        "DashboardDriverIndentDetailsCount": null,
        "DashboardChequeBookDetailsCount": null,
        "DashboardTADAAppliedDetailsCount": null,
        "DashboardVisitorAppointmentDetailsCount": null,
        "DashboardHWHealthcheckupdetailsCount": null,
        "hrremindersplannerdetails": null,
        "CloseTaskCoutnDetails": null,
        "Graduitydetails": null,
        "DashbaordTenantLeft": null,
        "DashbaordTenantTotalAmountPaid": null,
        "DashbaordTenantBalanceAmount": null,
        "DashbaordTenantJoined": null,
        "DashbaordTenantagreementend": null,
        "DashbaordTenantDetailsCount": null,
        "tenanttasklist": null,
        "Ratingfetchemployee": null,
        "emp_deatils": null,
        "HRME_QRCode": null,
        "Qrflag": false,
        "QRcode_emp_deatils": null,
        "HRMB_Id": 0,
        "HRMF_Id": 0,
        "HRMAR_Id": 0,
        "CURRENT_DATE": "0001-01-01T00:00:00",
        "QRcodeActivityDetails": null,
        "visitorcheckoutlist": null,
        "selectedEmpdetails": null,
        "GetReport": null,
        "RatingDetails": null,
        "Dashboardloandetails": null,
        "admindata": null,
        "type": null,
        "date": null,
        "CreatedDate": null,
        "UpdatedDate": null
        });

     qRcodeActivityDetails qrDetails = qRcodeActivityDetails.fromJson(response.data['qRcodeActivityDetails']);
     controller.securtyWorkList.addAll(qrDetails.values!);
      controller.updateLoading(false);
      for(int i = 0; i < qrDetails.values!.length; i++){
     controller.checkBox.add(true);
      }
      print(controller.checkBox.toString());
    return response.statusCode!;
  } on DioError catch (e) {
    controller.updateError(true);

    logger.e(e.message);
    return 0;
  } on Exception catch (e) {
    logger.e(e.toString());
    controller.updateError(true);

    return 0;
  }
}
