String jsonString = '''
    {
     "clientlist": {
    "\$type": "PreadmissionDTOs.com.vaps.FrontOffice.VMS_Attendance_GPSLocationDTO[], PreadmissionDTOs",
    "\$values": [
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 1,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Baldwin Girls High School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 2,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Baldwin Boys High School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 3,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Baldwin Co-Education Extn. High School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 4,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Hutchings High School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 5,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Jesus Sacred Heart",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 6,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "VIKASA SCHOOL",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 7,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "The Vikasa School & International school",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 8,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Bala Bharathi English Nursery and Primary Vivekananda High School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 9,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Bala Bharathi Kendriya Vidhyalaya",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 10,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Teresian College",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 11,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Sri Ramakrishna Vidyashala",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 12,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Baldwin Methodist College",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 13,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Baldwin International School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 14,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "MALDA",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 15,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Vanitha Seva Mandali English School (VSM)",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 16,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Janaseva Vidya Kendra",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 17,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Snehasagar Residential School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 18,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Sri Saraswathi Vidya Nikethan",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 19,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "HO",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 20,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "St. Mary's School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 21,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "St. James' School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 22,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "SS",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 23,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "ALL SCHOOL",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 24,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "VTS",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 25,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "MARGA",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 26,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "DRISTI",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 27,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "St.Philomina",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 28,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "HHS",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 34,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Jesus' Sacred Heart School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 37,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "St. Philomena P U College",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 38,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Baldwin Women's Methodist College",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 39,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Null",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 41,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "BWMC",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 46,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Sacred Heart Nursery School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 47,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "vikasa",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 48,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "VAPS HEAD OFFICE",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 86,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Notre Dame School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 92,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Vanitha Seva Mandira English School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 93,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Kalpataru College",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 95,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Baldwin Methodist Education Society",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 97,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Global Quality",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 98,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Meenakshi Academy of Higher Education and Research",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 99,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "BGS Global Institute of Medical Sciences",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 111,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "TMAES Academy of Science and commerce college",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 113,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "KUSMA",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 114,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Mandara Jnanadayini",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 115,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "SRI MOKSHAGUNDAM VISHWESWARAIAH VIDYA MANDIRA",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 117,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Vaps Tech Park",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 118,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "St Charles School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 120,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Y N CHIKKATTI PRE SCHOOL",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 121,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "KIADB",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 122,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Sai Nivas Apartment, Malleshwaram",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 124,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "SHASTRY CHARITABLE TRUST",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 125,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Amratha Bharathi Trust",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 126,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Vishwadarshana Education Society",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 127,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Nisarga Vidyanikethana English Medium High School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 128,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "NISARGA INDEPENDENT PU COLLEGE",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 131,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Smt Huvamma Chanchi Pratishtana (R)",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 135,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Sarvodaya Educational Trust (R)",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 136,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Jagruthi Educational Trust (R)",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 137,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Sahyadri English High school",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 138,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Chinmaya English Primary School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 139,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Chinmaya Vidyalaya",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 140,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "SBIOA English Medium School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 141,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "MJE Society’s Lions English Medium School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 142,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Sri Madhava Vidyalaya",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 143,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Vidyadayini Public School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 148,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "SBIOA English Medium School, Hubli",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 149,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Sri Kottala Basaveshwara Girls High School Sedam",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 150,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Kumudwathi Higher Primary School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 151,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Saraswathi Vidyalaya Siddapura",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 152,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Panduranga Ramana Nayaka Amrutha Bharathi Vidyalaya",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 153,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Sri Ganapathi  Primary School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 154,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Amratha Bharathi Vidyakendra(CBSE)",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 155,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Poornima English Medium School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 183,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Global Quality Training & assessors Pvt Ltd",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 184,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "LIONS ENGLISH MEDIUM SCHOOL",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 191,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "SOVATEC",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 193,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Smart Infrastructure And Services",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 199,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Janaseva PUC Residential College",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 209,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "VINAY CHIKKATTI ICSE SCHOOL",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 215,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "VINAY CHIKKATTI PU COLLEGE",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 221,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "BIPIN CHIKKATTI ENGLISH MEDIUM SCHOOL",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 227,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "BIPIN CHIKKATTI PU SCIENCE COLLEGE",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 233,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "BIPIN CHIKKATTI PRE SCHOOL",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 238,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "S Y CHIKKATTI PRE SCHOOL",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 239,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Sathya Sai Institutions",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 240,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Bharatiya Educational Society",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 243,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "SBG Vidyalaya BGS",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 245,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Bharathiya Vidya Kendra",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 257,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Dream Business Solution",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 258,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "ASISC",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 264,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Nagarjuna Pre University College yelahanaka",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 265,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Calcutta Girls High School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 266,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Unnathi Marketing",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 269,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "St Thomas Church School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 281,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Mount Hermon School Darjeeling",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 283,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Holycross Engineering College",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 289,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Maharishi Vidya Mandir Senior Secondary School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 294,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Nagarjuna Pre University College Chickballapur",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 296,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Kamala Nehru Education Society",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 300,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Shridevi  Institute of Engineering  and Technology",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 302,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Sathya Sai - BRNVN",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 310,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Nagarjuna Degree College yelahanaka",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 311,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "MJE LIONS SCHOOL",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 312,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "SREE RUDRESHWARA SCHOO",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 313,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "NAGARJUNA COLLEGE OF MANAGEMENT & STUDIES  CHIKKABALLAPURA",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 318,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Community Group of Institutions",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 323,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "House of Raadhya",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 325,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Shree Nandi Residential School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 330,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Zita Nursery and Primary School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 335,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Delhi Public School Beeramguda",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 336,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Sarvodaya School and PU College",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 337,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "JSS PHARMACY COLLEGE",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 338,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "SRI JNANAGANGOTRI INTERNATIONAL SCHOOL",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 339,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Tunbridge High School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 340,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Tagore Memorial English School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 341,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Nagarjuna Degree college",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 345,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Calcutta Boys School",
        "punchflag": false
      },
      {
        "vmsatgpsL_Id": 0,
        "mI_Id": 0,
        "hrmE_Id": 0,
        "ismmclT_Id": 353,
        "ismslE_Id": 0,
        "vmsatgpsL_ActiveFlg": false,
        "vmsatgpsL_CreatedBy": 0,
        "vmsatgpsL_UpdatedBy": 0,
        "userId": 0,
        "hrmE_MobileNo": 0,
        "ismmclT_ClientName": "Universal Group of Institutions",
        "punchflag": false
      }
    ]
  }
    }
  ''';
